name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifactName:
        description: "Name of the artifact to download"
        required: true
        type: string
        default: dist
    secrets:
      GITHUB_TOKEN:
        description: "GitHub Token"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
      - name: List Files
        run: ls -l
      - name: Output Information
        run: echo "Deploying..."
