name: Use Reusable Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "07-ExecutionFlow/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-ExecutionFlow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: 07-ExecutionFlow
        run: npm ci
      - name: Lint code
        working-directory: 07-ExecutionFlow
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-ExecutionFlow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: 07-ExecutionFlow
        run: npm ci
      - name: Test code
        working-directory: 07-ExecutionFlow
        id: run-test
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./07-ExecutionFlow/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-ExecutionFlow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: 07-ExecutionFlow
      - name: Build website
        id: build-website
        working-directory: 07-ExecutionFlow
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ./07-ExecutionFlow/dist
  deploy:
    needs: build
    uses: ./.github/workflows/07-reusable.yml
    with:
      artifactName: dist-files
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Deployment failed"
          echo ${{github}}
